# Generated by Django 4.2.13 on 2024-07-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("races", "0002_auto_20240705_1223"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
    ]
